import { useState, useCallback } from "react";
import TabSelector from "./components/TabSelector";
import TextPanel from "./components/TextPanel";
import ImagePanel from "./components/ImagePanel";
import VideoPanel from "./components/VideoPanel";
import AudioPanel from "./components/AudioPanel";

const TABS = ["text", "image", "video", "audio"];

let toastId = 0;

export default function App() {
  const [activeTab, setActiveTab] = useState("text");
  const [toasts, setToasts] = useState([]);

  const addToast = useCallback((message) => {
    const id = ++toastId;
    setToasts((prev) => [...prev, { id, message }]);
    setTimeout(() => {
      setToasts((prev) => prev.filter((t) => t.id !== id));
    }, 5000);
  }, []);

  return (
    <div className="app">
      {/* Header */}
      <header className="header">
        <h1 className="header-title">Ai TruthScan</h1>
        <p className="header-subtitle">AI Content Detection Engine</p>
        <div className="header-pills">
          <span className="pill">Text</span>
          <span className="pill">Images</span>
          <span className="pill">Video</span>
          <span className="pill">Audio</span>
        </div>
      </header>

      {/* Tab Selector */}
      <TabSelector activeTab={activeTab} setActiveTab={setActiveTab} />

      {/* Active Panel */}
      {activeTab === "text" && <TextPanel onError={addToast} />}
      {activeTab === "image" && <ImagePanel onError={addToast} />}
      {activeTab === "video" && <VideoPanel onError={addToast} />}
      {activeTab === "audio" && <AudioPanel onError={addToast} />}

      {/* Toast Notifications */}
      <div className="toast-container">
        {toasts.map((t) => (
          <div key={t.id} className="toast">
            <div className="toast-title">Error</div>
            {t.message}
          </div>
        ))}
      </div>

      {/* SEO Content Sections */}
      <main className="content-sections">
        {/* Features Section */}
        <section className="content-section" id="features">
          <div className="section-container">
            <h2 className="section-heading">
              Comprehensive AI Detection Across All Media Types
            </h2>
            <p className="section-intro">
              Ai TruthScan is a free, comprehensive AI content detection tool
              that helps you identify whether text, images, videos, or audio
              were generated by artificial intelligence or created by humans.
              Get instant results with detailed confidence scores and analysis
              signals.
            </p>

            <div className="features-grid">
              <article className="feature-card">
                <h3 className="feature-title">📝 AI Text Detection</h3>
                <p className="feature-description">
                  Detect AI-written content from ChatGPT, GPT-4, Claude, Gemini,
                  and other language models. Our system uses Hugging Face's
                  advanced transformer models (roberta-base-openai-detector)
                  with optional GPTZero integration to analyze writing patterns,
                  perplexity scores, burstiness, and vocabulary diversity.
                  Perfect for educators, content creators, and researchers
                  verifying authenticity.
                </p>
                <ul className="feature-signals">
                  <li>Sentence structure analysis</li>
                  <li>Vocabulary variety detection</li>
                  <li>Punctuation pattern recognition</li>
                  <li>Perplexity and burstiness scoring</li>
                  <li>Real-time probability calculation</li>
                </ul>
              </article>

              <article className="feature-card">
                <h3 className="feature-title">🖼️ AI Image Detection</h3>
                <p className="feature-description">
                  Identify AI-generated images from Midjourney, DALL-E, Stable
                  Diffusion, and other AI art generators. Powered by Hive AI and
                  AI-or-Not detection models, our tool examines pixel patterns,
                  EXIF metadata, compression artifacts, and visual
                  inconsistencies. Supports JPG, PNG, WEBP, and GIF formats up
                  to 20MB.
                </p>
                <ul className="feature-signals">
                  <li>EXIF metadata verification</li>
                  <li>AI artifact detection</li>
                  <li>Compression pattern analysis</li>
                  <li>Neural network fingerprinting</li>
                  <li>Multi-model consensus scoring</li>
                </ul>
              </article>

              <article className="feature-card">
                <h3 className="feature-title">🎬 AI Video Detection</h3>
                <p className="feature-description">
                  Detect deepfakes and AI-generated videos with frame-by-frame
                  analysis. Our system extracts keyframes using OpenCV and
                  applies image detection algorithms to identify synthetic
                  content, face swaps, and AI-manipulated footage. Supports MP4,
                  MOV, and WEBM files up to 500MB.
                </p>
                <ul className="feature-signals">
                  <li>Frame extraction and sampling</li>
                  <li>Temporal consistency checks</li>
                  <li>Face manipulation detection</li>
                  <li>Motion pattern analysis</li>
                  <li>Aggregate confidence scoring</li>
                </ul>
              </article>

              <article className="feature-card">
                <h3 className="feature-title">🎵 AI Audio Detection</h3>
                <p className="feature-description">
                  Identify AI-generated voices and synthetic speech from
                  ElevenLabs, voice cloning tools, and text-to-speech systems.
                  Using librosa acoustic analysis, we detect unnatural pitch
                  consistency, missing background noise, spectral anomalies, and
                  synthetic breath patterns. Supports MP3, WAV, AAC, and FLAC up
                  to 100MB.
                </p>
                <ul className="feature-signals">
                  <li>Acoustic fingerprint analysis</li>
                  <li>Background noise profiling</li>
                  <li>Pitch consistency detection</li>
                  <li>Spectral flatness measurement</li>
                  <li>Zero-crossing rate analysis</li>
                </ul>
              </article>
            </div>
          </div>
        </section>

        {/* How It Works Section */}
        <section className="content-section alt-bg" id="how-it-works">
          <div className="section-container">
            <h2 className="section-heading">
              How Ai TruthScan Works: AI Detection Made Simple
            </h2>
            <p className="section-intro">
              Our multi-layered detection system combines state-of-the-art
              machine learning models, heuristic analysis, and metadata
              examination to provide accurate AI content detection across all
              media types.
            </p>

            <div className="steps-container">
              <div className="step">
                <div className="step-number">1</div>
                <h3 className="step-title">Upload Your Content</h3>
                <p className="step-description">
                  Simply paste text, drag and drop files, or upload media
                  directly from your device. Ai TruthScan accepts text input of
                  any length, images up to 20MB, videos up to 500MB, and audio
                  files up to 100MB. No registration or account required.
                </p>
              </div>

              <div className="step">
                <div className="step-number">2</div>
                <h3 className="step-title">AI Analysis Engine</h3>
                <p className="step-description">
                  Our backend processes your content using specialized detection
                  models: Hugging Face transformers for text, Hive AI for
                  images, OpenCV frame analysis for video, and librosa acoustic
                  profiling for audio. Each model is optimized for its specific
                  content type.
                </p>
              </div>

              <div className="step">
                <div className="step-number">3</div>
                <h3 className="step-title">Get Detailed Results</h3>
                <p className="step-description">
                  Receive instant results with AI probability scores (0-100%),
                  human probability scores, confidence ratings, and detailed
                  detection signals. Results include processing time, model
                  information, and specific indicators that influenced the
                  verdict (AI, Human, or Mixed).
                </p>
              </div>

              <div className="step">
                <div className="step-number">4</div>
                <h3 className="step-title">Interpret & Act</h3>
                <p className="step-description">
                  Use the detailed breakdown to understand why content was
                  flagged. Color-coded severity indicators (red for high AI
                  signals, yellow for medium, green for human indicators) help
                  you make informed decisions. Results are probabilistic
                  guidance, not definitive proof.
                </p>
              </div>
            </div>

            <div className="tech-stack">
              <h3 className="tech-heading">Technology Stack</h3>
              <div className="tech-tags">
                <span className="tech-tag">Hugging Face Transformers</span>
                <span className="tech-tag">GPTZero API (Optional)</span>
                <span className="tech-tag">Hive AI Moderation</span>
                <span className="tech-tag">AI-or-Not Detection</span>
                <span className="tech-tag">OpenCV Frame Analysis</span>
                <span className="tech-tag">Librosa Acoustic Analysis</span>
                <span className="tech-tag">FastAPI Backend</span>
                <span className="tech-tag">React Frontend</span>
              </div>
            </div>
          </div>
        </section>

        {/* Use Cases Section */}
        <section className="content-section" id="use-cases">
          <div className="section-container">
            <h2 className="section-heading">
              Who Uses Ai TruthScan? Real-World Applications
            </h2>

            <div className="use-cases-grid">
              <article className="use-case-card">
                <h3 className="use-case-title">
                  🎓 Education & Academic Integrity
                </h3>
                <p className="use-case-description">
                  Teachers, professors, and academic institutions use Ai
                  TruthScan to verify student submissions and maintain academic
                  honesty. Detect AI-written essays, research papers, and
                  assignments from ChatGPT, Claude, or other LLMs. Helps
                  educators identify when students may be using AI writing tools
                  inappropriately.
                </p>
                <div className="use-case-examples">
                  <strong>Common Uses:</strong> Essay verification, homework
                  checks, thesis screening, plagiarism investigation
                </div>
              </article>

              <article className="use-case-card">
                <h3 className="use-case-title">
                  📰 Journalism & Media Verification
                </h3>
                <p className="use-case-description">
                  Journalists, fact-checkers, and media organizations verify
                  image authenticity, detect deepfake videos, and identify
                  AI-generated misinformation. Essential for combating fake
                  news, verifying sources, and maintaining journalistic
                  integrity in the age of synthetic media.
                </p>
                <div className="use-case-examples">
                  <strong>Common Uses:</strong> Photo verification, deepfake
                  detection, source authentication, misinformation combat
                </div>
              </article>

              <article className="use-case-card">
                <h3 className="use-case-title">
                  💼 Content Creation & Marketing
                </h3>
                <p className="use-case-description">
                  Content creators, marketers, and brand managers ensure content
                  authenticity and compliance with platform guidelines. Verify
                  that outsourced content meets quality standards, detect
                  unauthorized AI usage, and maintain brand voice consistency
                  across all content types.
                </p>
                <div className="use-case-examples">
                  <strong>Common Uses:</strong> Content auditing, vendor
                  verification, brand protection, platform compliance
                </div>
              </article>

              <article className="use-case-card">
                <h3 className="use-case-title">⚖️ Legal & Compliance</h3>
                <p className="use-case-description">
                  Legal professionals verify evidence authenticity in cases
                  involving digital media. Detect manipulated images, deepfake
                  videos, or AI-generated documents that could impact legal
                  proceedings. Useful for forensic analysis and evidentiary
                  verification.
                </p>
                <div className="use-case-examples">
                  <strong>Common Uses:</strong> Evidence verification, forensic
                  analysis, fraud detection, digital authenticity
                </div>
              </article>

              <article className="use-case-card">
                <h3 className="use-case-title">🔍 Research & Academia</h3>
                <p className="use-case-description">
                  Researchers studying AI detection, synthetic media, and
                  digital forensics use Ai TruthScan for testing and validation.
                  Analyze detection accuracy, compare models, and contribute to
                  the understanding of AI-generated content characteristics.
                </p>
                <div className="use-case-examples">
                  <strong>Common Uses:</strong> AI research, detection model
                  testing, dataset creation, academic studies
                </div>
              </article>

              <article className="use-case-card">
                <h3 className="use-case-title">🏢 Enterprise & HR</h3>
                <p className="use-case-description">
                  HR departments and recruiters verify candidate portfolios,
                  interview responses, and submission authenticity. Detect
                  AI-generated cover letters, assess genuine creative work, and
                  ensure candidate submissions reflect actual skills and
                  capabilities.
                </p>
                <div className="use-case-examples">
                  <strong>Common Uses:</strong> Resume screening, portfolio
                  verification, candidate assessment, skill validation
                </div>
              </article>
            </div>
          </div>
        </section>

        {/* FAQ Section */}
        <section className="content-section alt-bg" id="faq">
          <div className="section-container">
            <h2 className="section-heading">Frequently Asked Questions</h2>

            <div className="faq-container">
              <details className="faq-item" open>
                <summary className="faq-question">
                  How does Ai TruthScan detect AI-generated content?
                </summary>
                <div className="faq-answer">
                  <p>
                    Ai TruthScan uses multiple specialized AI detection models
                    tailored to each content type:
                  </p>
                  <ul>
                    <li>
                      <strong>Text:</strong> Hugging Face's
                      roberta-base-openai-detector analyzes writing patterns,
                      vocabulary diversity, sentence structure, and linguistic
                      markers characteristic of AI language models like ChatGPT,
                      GPT-4, Claude, and Gemini.
                    </li>
                    <li>
                      <strong>Images:</strong> Hive AI and AI-or-Not models
                      examine pixel patterns, compression artifacts, EXIF
                      metadata, and neural network fingerprints to identify
                      output from Midjourney, DALL-E, Stable Diffusion, etc.
                    </li>
                    <li>
                      <strong>Video:</strong> Frame extraction via OpenCV
                      followed by image detection on sampled frames to identify
                      deepfakes, face swaps, and AI-generated footage.
                    </li>
                    <li>
                      <strong>Audio:</strong> Librosa acoustic analysis detects
                      unnatural pitch consistency, missing background noise,
                      spectral anomalies, and synthetic speech patterns from
                      voice cloning and TTS systems.
                    </li>
                  </ul>
                  <p>
                    Each model provides a probability score (0-100%) indicating
                    confidence that content is AI-generated, along with specific
                    detection signals explaining the verdict.
                  </p>
                </div>
              </details>

              <details className="faq-item">
                <summary className="faq-question">
                  Is Ai TruthScan free to use? Are there any limitations?
                </summary>
                <div className="faq-answer">
                  <p>
                    Yes, Ai TruthScan is completely free to use with no
                    registration, subscription, or payment required. You can
                    analyze unlimited content across all four media types (text,
                    images, video, audio).
                  </p>
                  <p>
                    <strong>File size limits:</strong>
                  </p>
                  <ul>
                    <li>Text: No size limit</li>
                    <li>Images: Up to 20MB (JPG, PNG, WEBP, GIF)</li>
                    <li>Video: Up to 500MB (MP4, MOV, WEBM)</li>
                    <li>Audio: Up to 100MB (MP3, WAV, AAC, FLAC)</li>
                  </ul>
                  <p>
                    Processing times vary based on file size and server load,
                    typically ranging from 1-10 seconds for most requests.
                  </p>
                </div>
              </details>

              <details className="faq-item">
                <summary className="faq-question">
                  How accurate is AI content detection?
                </summary>
                <div className="faq-answer">
                  <p>
                    Detection accuracy varies based on content type, quality,
                    and sophistication of the AI tool used to generate it:
                  </p>
                  <ul>
                    <li>
                      <strong>Text detection:</strong> 70-95% accuracy for
                      clearly AI-generated or clearly human text. Mixed or
                      edited content is harder to classify.
                    </li>
                    <li>
                      <strong>Image detection:</strong> 80-95% accuracy for
                      obvious AI art. Subtle edits, compression, or hybrid
                      workflows reduce accuracy.
                    </li>
                    <li>
                      <strong>Video detection:</strong> 75-90% accuracy
                      depending on video quality and manipulation
                      sophistication.
                    </li>
                    <li>
                      <strong>Audio detection:</strong> 65-85% accuracy.
                      High-quality voice clones are increasingly difficult to
                      detect.
                    </li>
                  </ul>
                  <p>
                    <strong>Important:</strong> Ai TruthScan provides
                    probability scores and detection signals as guidance, not
                    definitive proof. Results should be interpreted alongside
                    human judgment and contextual factors. AI detection is an
                    evolving field, and no tool is 100% accurate.
                  </p>
                </div>
              </details>

              <details className="faq-item">
                <summary className="faq-question">
                  What do the detection signals mean?
                </summary>
                <div className="faq-answer">
                  <p>
                    Detection signals are specific indicators that influenced
                    the AI detection verdict. Each signal has a severity rating:
                  </p>
                  <ul>
                    <li>
                      <strong className="severity-high">High (Red):</strong>{" "}
                      Strong indicators of AI generation (e.g., "Low perplexity
                      score", "Unnatural pitch consistency", "No background
                      noise")
                    </li>
                    <li>
                      <strong className="severity-medium">
                        Medium (Yellow):
                      </strong>{" "}
                      Moderate indicators that suggest possible AI involvement
                      (e.g., "Low vocabulary variety", "Waveform
                      irregularities")
                    </li>
                    <li>
                      <strong className="severity-low">Low (Green):</strong>{" "}
                      Indicators suggesting human creation (e.g., "Natural
                      sentence variety", "EXIF metadata present", "Background
                      ambience detected")
                    </li>
                  </ul>
                  <p>
                    Multiple high-severity signals together increase confidence
                    in an "AI" verdict, while low-severity signals support a
                    "Human" verdict. "Mixed" verdicts indicate uncertainty or
                    hybrid content.
                  </p>
                </div>
              </details>

              <details className="faq-item">
                <summary className="faq-question">
                  Can Ai TruthScan detect all AI tools (ChatGPT, Claude,
                  Midjourney, etc.)?
                </summary>
                <div className="faq-answer">
                  <p>
                    Ai TruthScan's models are trained to detect patterns common
                    across multiple AI generation tools:
                  </p>
                  <ul>
                    <li>
                      <strong>Text AI:</strong> ChatGPT (GPT-3.5, GPT-4),
                      Claude, Gemini, LLaMA, Mistral, and other large language
                      models
                    </li>
                    <li>
                      <strong>Image AI:</strong> Midjourney, DALL-E 2/3, Stable
                      Diffusion, Leonardo.ai, and similar AI art generators
                    </li>
                    <li>
                      <strong>Video AI:</strong> Deepfakes, Runway ML,
                      Synthesia, D-ID, and face-swap technologies
                    </li>
                    <li>
                      <strong>Audio AI:</strong> ElevenLabs, voice cloning
                      tools, TTS systems, and synthetic speech generators
                    </li>
                  </ul>
                  <p>
                    However, detection becomes harder as AI tools improve and
                    when humans edit AI-generated content. Newer, more
                    sophisticated models may evade detection better than older
                    ones.
                  </p>
                </div>
              </details>

              <details className="faq-item">
                <summary className="faq-question">
                  Is my uploaded content stored or shared?
                </summary>
                <div className="faq-answer">
                  <p>Ai TruthScan prioritizes user privacy:</p>
                  <ul>
                    <li>
                      Content is processed in real-time and not permanently
                      stored on our servers
                    </li>
                    <li>
                      Files are temporarily held in memory during analysis and
                      deleted immediately after results are returned
                    </li>
                    <li>
                      We do not log, save, or share your text, images, videos,
                      or audio with third parties
                    </li>
                    <li>No user accounts or tracking cookies are used</li>
                    <li>
                      Analysis is performed server-side with secure HTTPS
                      connections
                    </li>
                  </ul>
                  <p>
                    For maximum privacy, avoid uploading sensitive,
                    confidential, or personal information. While we don't store
                    content, data passes through our servers for processing.
                  </p>
                </div>
              </details>

              <details className="faq-item">
                <summary className="faq-question">
                  Can AI detection be fooled or bypassed?
                </summary>
                <div className="faq-answer">
                  <p>
                    Yes, AI detection can be evaded through various techniques:
                  </p>
                  <ul>
                    <li>
                      <strong>Human editing:</strong> Manually rewriting AI text
                      or retouching AI images reduces detection accuracy
                    </li>
                    <li>
                      <strong>Paraphrasing tools:</strong> Some tools claim to
                      "humanize" AI text, though effectiveness varies
                    </li>
                    <li>
                      <strong>Hybrid workflows:</strong> Combining human and AI
                      work creates "mixed" content that's harder to classify
                    </li>
                    <li>
                      <strong>Advanced prompting:</strong> Sophisticated prompts
                      can produce more human-like AI output
                    </li>
                    <li>
                      <strong>Compression/editing:</strong> Re-encoding
                      images/video or applying filters can mask AI artifacts
                    </li>
                  </ul>
                  <p>
                    AI detection is a cat-and-mouse game. As detection improves,
                    so do evasion techniques. Ai TruthScan continuously updates
                    models to maintain effectiveness, but no detector is
                    foolproof.
                  </p>
                </div>
              </details>

              <details className="faq-item">
                <summary className="faq-question">
                  What browsers and devices are supported?
                </summary>
                <div className="faq-answer">
                  <p>
                    Ai TruthScan works on any modern web browser with JavaScript
                    enabled:
                  </p>
                  <ul>
                    <li>
                      <strong>Desktop:</strong> Chrome, Firefox, Safari, Edge,
                      Opera (latest 2 versions)
                    </li>
                    <li>
                      <strong>Mobile:</strong> iOS Safari, Chrome for Android,
                      Samsung Internet
                    </li>
                    <li>
                      <strong>Operating Systems:</strong> Windows, macOS, Linux,
                      iOS, Android
                    </li>
                  </ul>
                  <p>
                    For best performance, we recommend desktop browsers with
                    stable internet connections. Large file uploads (especially
                    video) may be slow on mobile networks.
                  </p>
                </div>
              </details>

              <details className="faq-item">
                <summary className="faq-question">
                  How can I improve detection accuracy?
                </summary>
                <div className="faq-answer">
                  <p>To get the most accurate results from Ai TruthScan:</p>
                  <ul>
                    <li>
                      <strong>Text:</strong> Submit complete paragraphs or
                      documents (100+ words) rather than short sentences. More
                      context improves accuracy.
                    </li>
                    <li>
                      <strong>Images:</strong> Upload high-resolution,
                      uncompressed originals when possible. Avoid heavily edited
                      or filtered images.
                    </li>
                    <li>
                      <strong>Video:</strong> Provide longer clips (10+ seconds)
                      with clear frames. Low-quality or heavily compressed video
                      reduces accuracy.
                    </li>
                    <li>
                      <strong>Audio:</strong> Upload clear, unedited recordings.
                      Background noise, music, or poor quality affects
                      detection.
                    </li>
                  </ul>
                  <p>
                    Remember: Results are probabilistic. Use Ai TruthScan as one
                    data point alongside critical thinking, source verification,
                    and contextual analysis.
                  </p>
                </div>
              </details>
            </div>
          </div>
        </section>

        {/* About Section - Improved */}
        <section className="content-section" id="about">
          <div className="section-container">
            <h2 className="section-heading">About Ai TruthScan</h2>
            <p className="section-intro">
              Empowering transparency in AI-generated content detection through
              open-source technology and privacy-first principles.
            </p>

            <div className="about-grid">
              {/* Mission Card */}
              <article className="about-card">
                <div className="about-card-icon">🎯</div>
                <h3 className="about-card-title">Our Mission</h3>
                <p className="about-card-text">
                  Ai TruthScan democratizes AI detection technology by providing
                  free, accessible tools for distinguishing AI-generated content
                  from human-created work. As AI tools like ChatGPT, Midjourney,
                  and voice cloning become mainstream, we bridge the gap between
                  expensive enterprise solutions and the needs of students,
                  educators, journalists, and independent creators.
                </p>
              </article>

              {/* Privacy Card */}
              <article className="about-card">
                <div className="about-card-icon">🔒</div>
                <h3 className="about-card-title">Privacy-First Design</h3>
                <p className="about-card-text">
                  Built on open-source technologies with zero data retention. We
                  don't store your content, require registration, or track user
                  behavior. Content is processed in real-time, deleted
                  immediately after analysis, and never shared with third
                  parties. All analysis happens server-side with secure HTTPS
                  connections.
                </p>
              </article>

              {/* Technology Card */}
              <article className="about-card">
                <div className="about-card-icon">⚙️</div>
                <h3 className="about-card-title">Advanced Technology Stack</h3>
                <p className="about-card-text">
                  Powered by industry-leading AI models including Hugging Face
                  transformers, Hive AI, OpenCV, and Librosa. Our React frontend
                  delivers fast, responsive experiences while our FastAPI
                  backend ensures scalable, accurate detection across text,
                  images, video, and audio.
                </p>
              </article>

              {/* Self-Hostable Card */}
              <article className="about-card">
                <div className="about-card-icon">🚀</div>
                <h3 className="about-card-title">
                  Self-Hostable & Customizable
                </h3>
                <p className="about-card-text">
                  Organizations can deploy Ai TruthScan on their own
                  infrastructure, swap detection models, or integrate via our
                  REST API. Fully customizable for enterprise workflows while
                  maintaining the same powerful detection capabilities available
                  to individual users.
                </p>
              </article>
            </div>

            {/* Important Disclaimer */}
            <div className="about-disclaimer">
              <div className="disclaimer-header">
                <span className="disclaimer-icon">⚠️</span>
                <h3 className="disclaimer-title">
                  Important: Limitations & Responsible Use
                </h3>
              </div>
              <p className="disclaimer-text">
                AI detection is not foolproof. Ai TruthScan provides probability
                scores and detection signals as{" "}
                <strong>guidance, not definitive proof</strong> of AI
                authorship. Results should be interpreted responsibly:
              </p>
              <div className="disclaimer-grid">
                <div className="disclaimer-item">
                  <span className="disclaimer-bullet">❌</span>
                  <p>
                    <strong>False Positives:</strong> Human content may
                    occasionally be flagged as AI-generated
                  </p>
                </div>
                <div className="disclaimer-item">
                  <span className="disclaimer-bullet">⚡</span>
                  <p>
                    <strong>False Negatives:</strong> Sophisticated AI content
                    may evade detection systems
                  </p>
                </div>
                <div className="disclaimer-item">
                  <span className="disclaimer-bullet">🔍</span>
                  <p>
                    <strong>Context Matters:</strong> Consider content source,
                    purpose, and creator claims
                  </p>
                </div>
                <div className="disclaimer-item">
                  <span className="disclaimer-bullet">🔄</span>
                  <p>
                    <strong>Evolving Landscape:</strong> Detection accuracy
                    changes as AI tools improve
                  </p>
                </div>
              </div>
              <p className="disclaimer-warning">
                Ai TruthScan should not be the sole basis for academic
                penalties, legal decisions, or content moderation without
                additional evidence and human review.
              </p>
            </div>

            {/* Technology Partners */}
            <div className="about-tech">
              <h3 className="about-tech-title">
                Technology Partners & Attribution
              </h3>
              <div className="tech-partners-grid">
                <div className="tech-partner">
                  <strong>🤗 Hugging Face</strong>
                  <p>roberta-base-openai-detector for text classification</p>
                </div>
                <div className="tech-partner">
                  <strong>🔍 GPTZero</strong>
                  <p>Optional integration for advanced text detection</p>
                </div>
                <div className="tech-partner">
                  <strong>🐝 Hive AI</strong>
                  <p>Image moderation and AI detection API</p>
                </div>
                <div className="tech-partner">
                  <strong>🖼️ AI-or-Not</strong>
                  <p>Supplementary image authenticity verification</p>
                </div>
                <div className="tech-partner">
                  <strong>📹 OpenCV</strong>
                  <p>Video frame extraction and analysis</p>
                </div>
                <div className="tech-partner">
                  <strong>🎵 Librosa</strong>
                  <p>Audio feature extraction and acoustic analysis</p>
                </div>
              </div>
            </div>

            {/* Contact & Contributions */}
            <div className="about-contact">
              <h3 className="about-contact-title">Get Involved</h3>
              <p className="about-contact-text">
                Ai TruthScan is an evolving open-source project. We welcome
                feedback, bug reports, and feature requests from our community.
              </p>
              <div className="about-contact-buttons">
                <a
                  href="https://github.com/truthscan"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="contact-button primary"
                >
                  <span>GitHub Repository</span>
                </a>
                <a
                  href="/api/docs"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="contact-button secondary"
                >
                  <span>API Documentation</span>
                </a>
                <a
                  href="https://www.pixelpk.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="contact-button secondary"
                >
                  <span>Contact Pixelpk</span>
                </a>
              </div>
            </div>
          </div>
        </section>

        {/* Footer */}
        <footer className="footer">
          <div className="footer-content">
            <div className="footer-brand">
              <h4 className="footer-heading">Ai TruthScan</h4>
              <p className="footer-description">
                Free AI content detection for text, images, video, and audio.
                Powered by open-source technology and privacy-first principles.
              </p>
            </div>

            <div className="footer-links">
              <div className="footer-column">
                <h5 className="footer-link-title">Product</h5>
                <a href="#features">Features</a>
                <a href="#how-it-works">How it Works</a>
                <a href="#use-cases">Use Cases</a>
              </div>

              <div className="footer-column">
                <h5 className="footer-link-title">Resources</h5>
                <a href="#faq">FAQ</a>
                <a href="#about">About</a>
                <a href="/api/docs">API Docs</a>
              </div>

              <div className="footer-column">
                <h5 className="footer-link-title">Connect</h5>
                <a
                  href="https://github.com/truthscan"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  GitHub
                </a>
                <a
                  href="https://www.pixelpk.com"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Pixelpk
                </a>
              </div>
            </div>
          </div>

          <div className="footer-bottom">
            <p className="footer-disclaimer">
              Developed & Designed with ❤️ by{" "}
              <a
                href="https://www.pixelpk.com"
                target="_blank"
                rel="noopener noreferrer"
              >
                Pixelpk Technologies
              </a>
            </p>
            <p className="footer-copyright">
              © 2026 Ai TruthScan. Open-source AI detection tool. Results are
              probabilistic guidance, not definitive proof.
            </p>
          </div>
        </footer>
      </main>
    </div>
  );
}
